# 作業目標:

    通過建立多層的神經網路, 了解權值矩陣更新

# 作業重點: 

3  層神經網路

通過增加更多的中間層，以對更多關係的組合進行建模

syn1 權值矩陣將隱層的組合輸出映射到最終結果，

而在更新 syn1 的同時，還需要更新 syn0 權值矩陣，

以從輸入資料中更好地產生這些組合

In [14]:
import numpy as np
 
# Sigmoid 函數可以將任何值都映射到一個位於 0 到  1 範圍內的值。通過它，我們可以將實數轉化為概率值
def nonlin(x,deriv=False):
    if(deriv==True):
        return x*(1-x)
    return 1/(1+np.exp(-x))

X = np.array([  [0,0,1],
                [0,1,1],
                [1,0,1],
                [1,1,1] ])  
        
# define y for output dataset            
y = np.array([
    [0],
    [0],
    [1],
    [1]
])

In [20]:

# seed random numbers to make calculation
# deterministic (just a good practice)
np.random.seed(1)
#亂數設定產生種子得到的權重初始化集仍是隨機分佈的，
#但每次開始訓練時，得到的權重初始集分佈都是完全一致的。
 
# initialize weights randomly with mean 0
syn0 = 2*np.random.random((3,3)) - 1
# define syn1
syn1 = 2*np.random.random((3,1)) - 1

iter = 0
#該神經網路權重矩陣的初始化操作。
#用 “syn0” 來代指 (即“輸入層-第一層隱層”間權重矩陣）
#用 “syn1” 來代指 (即“輸入層-第二層隱層”間權重矩陣）
print(syn0)


[[-0.16595599  0.44064899 -0.99977125]
 [-0.39533485 -0.70648822 -0.81532281]
 [-0.62747958 -0.30887855 -0.20646505]]


神經網路訓練
for 迴圈反覆運算式地多次執行訓練代碼，使得我們的網路能更好地擬合訓練集

In [23]:
for iter in range(100000):
    # forward propagation
    l0 = X  # 一個 4 x 3 的矩陣，其實是有四筆測試資料，每一筆測試資料都是 3 個 Input
    l1 = nonlin(np.dot(l0,syn0))  # 把從 L0 來的每一筆測試資料乘上第一層的 weight 矩陣，得到一個 4 x 1 的矩陣。
    # 這樣第二層不就只有 1 個？
    l2 = nonlin(np.dot(l1, syn1))
    
    '''
    新增
    l2_error 該值說明了神經網路預測時“丟失”的數目。
    l2_delta 該值為經確信度加權後的神經網路的誤差，除了確信誤差很小時，它近似等於預測誤差。
    '''
 
    l2_error = y - l2
    l2_delta = l2_error * nonlin(l2, True)

    # how much did we miss?
    l1_error = l2_delta - l1
 
    # multiply how much we missed by the 
    # slope of the sigmoid at the values in l1
    l1_delta = l1_error * nonlin(l1,True)
    
    # update weights
    syn0 += np.dot(l0.T, l1_delta)
    # syn1 update weights
    syn1 += np.dot(l1.T, l2_delta)
    
print("Output After Training:")
print(l1, "\n\n", l1_error)
print("\n\n")
print(l2, "\n\n", l2_error)

print("\n\n")
print(syn0, "\n\n", syn1)

Output After Training:
[[5.54228463e-05 5.54103648e-05 5.70217151e-05]
 [5.45572855e-05 5.45458828e-05 5.60140636e-05]
 [1.08295769e-02 1.08295673e-02 1.08308578e-02]
 [1.06622412e-02 1.06624027e-02 1.06414879e-02]] 

 [[-0.12572714 -0.12572713 -0.12572874]
 [-0.12571544 -0.12571543 -0.1257169 ]
 [-0.00012736 -0.00012735 -0.00012864]
 [ 0.00065565  0.00065549  0.0006764 ]]



[[0.50270154]
 [0.50265774]
 [0.89036404]
 [0.88704378]] 

 [[-0.50270154]
 [-0.50265774]
 [ 0.10963596]
 [ 0.11295622]]



[[ 5.28588315  5.28610749  5.25756104]
 [-0.01574144 -0.01572524 -0.0178303 ]
 [-9.80047151 -9.80069675 -9.77202984]] 

 [[68.64471064]
 [69.3452957 ]
 [55.40645921]]
