## 練習時間
假設我們資料中類別的數量並不均衡，在評估準確率時可能會有所偏頗，試著切分出 y_test 中，0 類別與 1 類別的數量是一樣的 (亦即 y_test 的類別是均衡的)

In [3]:
import numpy as np
from sklearn.model_selection import train_test_split, KFold
X = np.arange(1000).reshape(200, 5)
y = np.zeros(200)
y[:40] = 1

In [2]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

可以看見 y 類別中，有 160 個 類別 0，40 個 類別 1 ，請試著使用 train_test_split 函數，切分出 y_test 中能各有 10 筆類別 0 與 10 筆類別 1 。(HINT: 參考函數中的 test_size，可針對不同類別各自作切分後再合併)

In [32]:
# Take 10 class 1 from 0 ~ 39
X_train_1, X_test_1, Y_train_1, Y_test_1 = train_test_split(X[:40], y[:40], test_size=10)
# Take 10 class 0 from 40 ~ 199
X_train_2, X_test_2, Y_train_2, Y_test_2 = train_test_split(X[40:], y[40:], test_size=10)


X_train = np.concatenate((X_train_1, X_train_2))
Y_train = np.concatenate((Y_train_1, Y_train_2))
print(X_train[:10])
print(Y_train[:10])

# testset 有平衡了，但是 Train set 沒有捏
X_test = np.concatenate((X_test_1, X_test_2))
Y_test = np.concatenate((Y_test_1, Y_test_2))
print(X_test)
print(Y_test)

[[ 25  26  27  28  29]
 [155 156 157 158 159]
 [140 141 142 143 144]
 [ 85  86  87  88  89]
 [120 121 122 123 124]
 [ 40  41  42  43  44]
 [170 171 172 173 174]
 [185 186 187 188 189]
 [145 146 147 148 149]
 [ 15  16  17  18  19]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[110 111 112 113 114]
 [  0   1   2   3   4]
 [ 80  81  82  83  84]
 [105 106 107 108 109]
 [135 136 137 138 139]
 [ 60  61  62  63  64]
 [ 95  96  97  98  99]
 [165 166 167 168 169]
 [160 161 162 163 164]
 [115 116 117 118 119]
 [830 831 832 833 834]
 [295 296 297 298 299]
 [745 746 747 748 749]
 [400 401 402 403 404]
 [480 481 482 483 484]
 [945 946 947 948 949]
 [415 416 417 418 419]
 [925 926 927 928 929]
 [550 551 552 553 554]
 [220 221 222 223 224]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
